version: '3'

services:
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: dockers/app/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - bundle_data:/bundle
    command: sh /scripts/command.sh

  db:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/

volumes:
  bundle_data:
